"""Schema introspection for the Target Scheduler database.

We deliberately derive the schema from the *actual* database file via SQLite
``PRAGMA`` calls rather than trusting documentation. The reader uses this to map
columns case-insensitively, so it keeps working even if column casing or presence
varies across Target Scheduler versions.

Run directly to dump the schema and (re)generate ``SCHEMA.md``:

    uv run python -m app.db.introspect
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass, field
from pathlib import Path

from ..config import REPO_ROOT
from .working_copy import connect_readonly, get_working_copy


@dataclass
class Column:
    name: str
    type: str
    notnull: bool
    default: str | None
    pk: bool


@dataclass
class ForeignKey:
    column: str
    ref_table: str
    ref_column: str


@dataclass
class Table:
    name: str
    columns: list[Column] = field(default_factory=list)
    foreign_keys: list[ForeignKey] = field(default_factory=list)
    row_count: int = 0

    def column_names(self) -> list[str]:
        return [c.name for c in self.columns]


def introspect(conn: sqlite3.Connection) -> dict[str, Table]:
    """Return a map of table name -> Table for all user tables."""
    tables: dict[str, Table] = {}
    names = [
        r[0]
        for r in conn.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
    ]
    for name in names:
        t = Table(name=name)
        for r in conn.execute(f'PRAGMA table_info("{name}")'):
            t.columns.append(
                Column(
                    name=r["name"],
                    type=r["type"],
                    notnull=bool(r["notnull"]),
                    default=r["dflt_value"],
                    pk=bool(r["pk"]),
                )
            )
        for r in conn.execute(f'PRAGMA foreign_key_list("{name}")'):
            t.foreign_keys.append(
                ForeignKey(column=r["from"], ref_table=r["table"], ref_column=r["to"])
            )
        t.row_count = conn.execute(f'SELECT COUNT(*) FROM "{name}"').fetchone()[0]
        tables[name] = t
    return tables


def render_markdown(tables: dict[str, Table]) -> str:
    lines = [
        "# Target Scheduler database schema (introspected)",
        "",
        "_Auto-generated by `app.db.introspect` from the sample database. "
        "Do not hand-edit._",
        "",
    ]
    for t in tables.values():
        lines.append(f"## `{t.name}`  ({t.row_count} rows)")
        lines.append("")
        lines.append("| column | type | not null | pk | default |")
        lines.append("|---|---|---|---|---|")
        for c in t.columns:
            lines.append(
                f"| `{c.name}` | {c.type or '—'} | {'✓' if c.notnull else ''} "
                f"| {'✓' if c.pk else ''} | {c.default if c.default is not None else ''} |"
            )
        if t.foreign_keys:
            lines.append("")
            lines.append("Foreign keys:")
            for fk in t.foreign_keys:
                lines.append(f"- `{fk.column}` → `{fk.ref_table}.{fk.ref_column}`")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    wc = get_working_copy()
    if wc is None:
        print(
            "No source database found. Drop a schedulerdb.sqlite into "
            "sample_database/ (or set TS_ASSISTANT_DB) and re-run."
        )
        return 1
    with connect_readonly(wc) as conn:
        tables = introspect(conn)
    md = render_markdown(tables)
    out = REPO_ROOT / "SCHEMA.md"
    out.write_text(md)
    print(f"Introspected {len(tables)} tables -> {out}")
    for t in tables.values():
        print(f"  {t.name:24} {t.row_count:6} rows  "
              f"[{', '.join(t.column_names())}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
